# Generated by Django 2.2.4 on 2020-04-09 12:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200409_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_player_in',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='is_group_formed',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
